### ISSUE TITLE
Release for Swift 4.2

### ISSUE THREAD

**Issue by DominicMDev** [bradhilton/AssociatedValues#4]
Hey @bradhilton,
I was wondering if you could push a new release with the Swift 4.2 changes you pulled in from my fork.

**Comment by JettF** [comment]
It'd be awesome to see that release. I am in the middle of converting to 4.2 and AssociatedValues is one of the only ones left.

**Comment by bradhilton** [comment]
@DominicMDev @JettF I just pushed a new release.

**Comment by JettF** [comment]
Thank you!!
